name: level-up-your-python
channels:
  - conda-forge
dependencies:
  - black
  - ipykernel >=6.0
  - ipython >=8.0
  - ipywidgets
  - jupyter-book
  - jupyterlab >=3
  - line_profiler
  - matplotlib >=3.5
  - mypy >=0.9r760
  - nb_conda_kernels
  - numba >=0.55
  - numpy >=1.20
  - pandas >=1.3
  - pip
  - pybind11 >=2.10
  - pytest >7
  - pytest-mock
  - python ==3.10.*
  - rich >=11
